### ISSUE TITLE
Scannet dataset

### ISSUE THREAD

**Issue by youngju-na** [dvlab-research/TriVol#3]
Hi, thanks for sharing this work!
I want to know more about the details of scannet dataset.
Should I download the entire dataset (which takes more than 1TB)?
If not, could you guide me what commands should I use to download specific purpose of your method?

Thanks in advance :)

**Comment by tau-yihouxiang** [comment]
Yes, you need to download the whole ScanNet v2 dataset and extract corresponding images, poses according to the official preprocess code. The dataset structure is:

```
── scannet
    └── scene0000_00
        ├── pose
              └──1.txt
         ├── intrinsic
              └──*.txt
        ├── color
               └──1.jpg
        └── scene0000_00_vh_clean_2.ply
        └── images.txt
    └── scene0000_01
```
